run:
  skip-files:
    - internal/templates/rice-box.go

linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - errcheck
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
