---
name: actionlint

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  lint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v2.3.4

      - name: Lint with actionlint
        uses: reviewdog/action-actionlint@f00ad0691526c10be4021a91b2510f0a769b14d0 # v1.14.0
