---
name: actionlint

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  lint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v2.3.4

      - name: Lint with actionlint
        uses: reviewdog/action-actionlint@0d952c597ef8459f634d7145b0b044a9699e5e43 # v1.14.0
